# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\py\nsa\nsaui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(487, 402)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/qwerty/Desktop/1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setSizeGripEnabled(True)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 10, 461, 381))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.LogFileButton = QtWidgets.QToolButton(self.widget)
        self.LogFileButton.setObjectName("LogFileButton")
        self.gridLayout.addWidget(self.LogFileButton, 5, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.ArchitecturecomboBox = QtWidgets.QComboBox(self.widget)
        self.ArchitecturecomboBox.setObjectName("ArchitecturecomboBox")
        self.ArchitecturecomboBox.addItem("")
        self.ArchitecturecomboBox.addItem("")
        self.gridLayout.addWidget(self.ArchitecturecomboBox, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.DllPathButton = QtWidgets.QToolButton(self.widget)
        self.DllPathButton.setObjectName("DllPathButton")
        self.gridLayout.addWidget(self.DllPathButton, 4, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.EternalblueButton = QtWidgets.QPushButton(self.widget)
        self.EternalblueButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.EternalblueButton.setObjectName("EternalblueButton")
        self.gridLayout.addWidget(self.EternalblueButton, 0, 3, 3, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.TargetOscomboBox = QtWidgets.QComboBox(self.widget)
        self.TargetOscomboBox.setObjectName("TargetOscomboBox")
        self.TargetOscomboBox.addItem("")
        self.TargetOscomboBox.addItem("")
        self.gridLayout.addWidget(self.TargetOscomboBox, 1, 1, 1, 1)
        self.TargetEdit = QtWidgets.QLineEdit(self.widget)
        self.TargetEdit.setObjectName("TargetEdit")
        self.gridLayout.addWidget(self.TargetEdit, 0, 1, 1, 1)
        self.ProcessNameEdit = QtWidgets.QLineEdit(self.widget)
        self.ProcessNameEdit.setObjectName("ProcessNameEdit")
        self.gridLayout.addWidget(self.ProcessNameEdit, 3, 1, 1, 1)
        self.LogFileEdit = QtWidgets.QLineEdit(self.widget)
        self.LogFileEdit.setObjectName("LogFileEdit")
        self.gridLayout.addWidget(self.LogFileEdit, 5, 1, 1, 1)
        self.DllPathEdit = QtWidgets.QLineEdit(self.widget)
        self.DllPathEdit.setObjectName("DllPathEdit")
        self.gridLayout.addWidget(self.DllPathEdit, 4, 1, 1, 1)
        self.DoublepulsarButton = QtWidgets.QPushButton(self.widget)
        self.DoublepulsarButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.DoublepulsarButton.setObjectName("DoublepulsarButton")
        self.gridLayout.addWidget(self.DoublepulsarButton, 3, 3, 3, 1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 3, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 6, 0, 1, 2)
        self.label.raise_()
        self.TargetEdit.raise_()
        self.label_2.raise_()
        self.DllPathEdit.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.TargetOscomboBox.raise_()
        self.ProcessNameEdit.raise_()
        self.textBrowser.raise_()
        self.DllPathButton.raise_()
        self.DllPathButton.raise_()
        self.EternalblueButton.raise_()
        self.DoublepulsarButton.raise_()
        self.LogFileEdit.raise_()
        self.label_5.raise_()
        self.LogFileButton.raise_()
        self.ArchitecturecomboBox.raise_()
        self.label_6.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "方程式漏洞利用工具    by Tr33"))
        Dialog.setWhatsThis(_translate("Dialog", "方程式漏洞利用工具    by Tr33"))
        self.LogFileButton.setText(_translate("Dialog", "..."))
        self.label.setText(_translate("Dialog", "Target:Port"))
        self.label_5.setText(_translate("Dialog", "LogFile"))
        self.ArchitecturecomboBox.setItemText(0, _translate("Dialog", "x64"))
        self.ArchitecturecomboBox.setItemText(1, _translate("Dialog", "x86"))
        self.label_2.setText(_translate("Dialog", "Dll:"))
        self.DllPathButton.setText(_translate("Dialog", "..."))
        self.label_3.setText(_translate("Dialog", "TargetOs:"))
        self.label_6.setText(_translate("Dialog", "Architecture:"))
        self.EternalblueButton.setText(_translate("Dialog", "Eternalblue"))
        self.label_4.setText(_translate("Dialog", "ProcessName:"))
        self.TargetOscomboBox.setItemText(0, _translate("Dialog", "WIN72K8R2"))
        self.TargetOscomboBox.setItemText(1, _translate("Dialog", "XP"))
        self.TargetEdit.setText(_translate("Dialog", "192.168.1.2:445"))
        self.ProcessNameEdit.setText(_translate("Dialog", "lsass.exe"))
        self.LogFileEdit.setText(_translate("Dialog", "D:/log.log"))
        self.DllPathEdit.setText(_translate("Dialog", "D:/test.dll"))
        self.DoublepulsarButton.setText(_translate("Dialog", "Doublepulsar"))
        self.label_7.setText(_translate("Dialog", "群：627149223"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

